# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gellert/Documents/assignment-impromptu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gellert/Documents/assignment-impromptu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gellert/Documents/assignment-impromptu/CMakeFiles /home/gellert/Documents/assignment-impromptu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gellert/Documents/assignment-impromptu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named rshellexe

# Build rule for target.
rshellexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rshellexe
.PHONY : rshellexe

# fast build rule for target.
rshellexe/fast:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/build
.PHONY : rshellexe/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f vendor/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make vendor/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f vendor/googletest/googlemock/CMakeFiles/gmock.dir/build.make vendor/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f vendor/googletest/googletest/CMakeFiles/gtest_main.dir/build.make vendor/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f vendor/googletest/googletest/CMakeFiles/gtest.dir/build.make vendor/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

RShell/src/AndOrSemicolon.o: RShell/src/AndOrSemicolon.cpp.o

.PHONY : RShell/src/AndOrSemicolon.o

# target to build an object file
RShell/src/AndOrSemicolon.cpp.o:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/AndOrSemicolon.cpp.o
.PHONY : RShell/src/AndOrSemicolon.cpp.o

RShell/src/AndOrSemicolon.i: RShell/src/AndOrSemicolon.cpp.i

.PHONY : RShell/src/AndOrSemicolon.i

# target to preprocess a source file
RShell/src/AndOrSemicolon.cpp.i:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/AndOrSemicolon.cpp.i
.PHONY : RShell/src/AndOrSemicolon.cpp.i

RShell/src/AndOrSemicolon.s: RShell/src/AndOrSemicolon.cpp.s

.PHONY : RShell/src/AndOrSemicolon.s

# target to generate assembly for a file
RShell/src/AndOrSemicolon.cpp.s:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/AndOrSemicolon.cpp.s
.PHONY : RShell/src/AndOrSemicolon.cpp.s

RShell/src/Command.o: RShell/src/Command.cpp.o

.PHONY : RShell/src/Command.o

# target to build an object file
RShell/src/Command.cpp.o:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/Command.cpp.o
.PHONY : RShell/src/Command.cpp.o

RShell/src/Command.i: RShell/src/Command.cpp.i

.PHONY : RShell/src/Command.i

# target to preprocess a source file
RShell/src/Command.cpp.i:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/Command.cpp.i
.PHONY : RShell/src/Command.cpp.i

RShell/src/Command.s: RShell/src/Command.cpp.s

.PHONY : RShell/src/Command.s

# target to generate assembly for a file
RShell/src/Command.cpp.s:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/Command.cpp.s
.PHONY : RShell/src/Command.cpp.s

RShell/src/CommandLine.o: RShell/src/CommandLine.cpp.o

.PHONY : RShell/src/CommandLine.o

# target to build an object file
RShell/src/CommandLine.cpp.o:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/CommandLine.cpp.o
.PHONY : RShell/src/CommandLine.cpp.o

RShell/src/CommandLine.i: RShell/src/CommandLine.cpp.i

.PHONY : RShell/src/CommandLine.i

# target to preprocess a source file
RShell/src/CommandLine.cpp.i:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/CommandLine.cpp.i
.PHONY : RShell/src/CommandLine.cpp.i

RShell/src/CommandLine.s: RShell/src/CommandLine.cpp.s

.PHONY : RShell/src/CommandLine.s

# target to generate assembly for a file
RShell/src/CommandLine.cpp.s:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/CommandLine.cpp.s
.PHONY : RShell/src/CommandLine.cpp.s

RShell/src/Connector.o: RShell/src/Connector.cpp.o

.PHONY : RShell/src/Connector.o

# target to build an object file
RShell/src/Connector.cpp.o:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/Connector.cpp.o
.PHONY : RShell/src/Connector.cpp.o

RShell/src/Connector.i: RShell/src/Connector.cpp.i

.PHONY : RShell/src/Connector.i

# target to preprocess a source file
RShell/src/Connector.cpp.i:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/Connector.cpp.i
.PHONY : RShell/src/Connector.cpp.i

RShell/src/Connector.s: RShell/src/Connector.cpp.s

.PHONY : RShell/src/Connector.s

# target to generate assembly for a file
RShell/src/Connector.cpp.s:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/Connector.cpp.s
.PHONY : RShell/src/Connector.cpp.s

RShell/src/main.o: RShell/src/main.cpp.o

.PHONY : RShell/src/main.o

# target to build an object file
RShell/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/main.cpp.o
.PHONY : RShell/src/main.cpp.o

RShell/src/main.i: RShell/src/main.cpp.i

.PHONY : RShell/src/main.i

# target to preprocess a source file
RShell/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/main.cpp.i
.PHONY : RShell/src/main.cpp.i

RShell/src/main.s: RShell/src/main.cpp.s

.PHONY : RShell/src/main.s

# target to generate assembly for a file
RShell/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rshellexe.dir/build.make CMakeFiles/rshellexe.dir/RShell/src/main.cpp.s
.PHONY : RShell/src/main.cpp.s

unit_test/unit_test.o: unit_test/unit_test.cpp.o

.PHONY : unit_test/unit_test.o

# target to build an object file
unit_test/unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test/unit_test.cpp.o
.PHONY : unit_test/unit_test.cpp.o

unit_test/unit_test.i: unit_test/unit_test.cpp.i

.PHONY : unit_test/unit_test.i

# target to preprocess a source file
unit_test/unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test/unit_test.cpp.i
.PHONY : unit_test/unit_test.cpp.i

unit_test/unit_test.s: unit_test/unit_test.cpp.s

.PHONY : unit_test/unit_test.s

# target to generate assembly for a file
unit_test/unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test/unit_test.cpp.s
.PHONY : unit_test/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rshellexe"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... RShell/src/AndOrSemicolon.o"
	@echo "... RShell/src/AndOrSemicolon.i"
	@echo "... RShell/src/AndOrSemicolon.s"
	@echo "... RShell/src/Command.o"
	@echo "... RShell/src/Command.i"
	@echo "... RShell/src/Command.s"
	@echo "... RShell/src/CommandLine.o"
	@echo "... RShell/src/CommandLine.i"
	@echo "... RShell/src/CommandLine.s"
	@echo "... RShell/src/Connector.o"
	@echo "... RShell/src/Connector.i"
	@echo "... RShell/src/Connector.s"
	@echo "... RShell/src/main.o"
	@echo "... RShell/src/main.i"
	@echo "... RShell/src/main.s"
	@echo "... unit_test/unit_test.o"
	@echo "... unit_test/unit_test.i"
	@echo "... unit_test/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

